import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en": {
          "1": "Choose your language",
          "2": "Find your favorite  items",
          "3":
              "Find  your  favourite  products  \n that  you  need  to  buy  daily.",
          "4": "Easy & Safe Payment",
          "5": "Pay  for  the  products  you  buy  \n safely  &  easily",
          "6": "Product  Delivery",
          "7": "Your  products  are  delivered \n home  safely  &  securely",
          "8": "Next",
          "9": "Sign in",
          "10": "Welcome Back",
          "11":
              "Signin with email and password \n or countine with scocial media",
          "12": "Email",
          "13": "Enter your email",
          "14": "Password",
          "15": "Enter your password",
          "16": "Dont Have An Account ? ",
          "17": "SignUp",
          "18": "Forgot Password",
          "19": "Welcome to you ",
          "20":
              "Sign Up With Your Email And Password OR Continue With Social Media",
          "21": "Username",
          "22": "Enter your Username",
          "23": "Phone",
          "24": "Enter your Phone",
          "25": "have an account ?",
          "26": "Check Email",
          "27": " Enter A verification code",
          "28": "Account successfully created",
          "29": "please Enter Your Email Address To Recive A verification code",
          "30": "check",
          "31": "Go To Login",
          "32": "Success",
          "33": "save",
          "34": "Please Enter new Password",
          "35": "New Password",
          "36": "Password has been reset successfully",
          "37": "congratulations",
          "38": "successfully registered",
          "39": "Reset Password",
          "40": "New password",
          "41": "Enter your new password",
          "42": "Repassword",
          "43": "Enter your Repassword",
          "44": "Reset",
          "45": "Enter your email to check ",
          "46": "This value is not user name",
          "47": "This value is not Email",
          "48": "This value is not password",
          "49": "This value is not phone",
          "50": "You cannot enter a value smaller than ",
          "51": "You cannot enter a value greater than",
          "52": "You cannot enter a null value",
          "53": "warning",
          "54": "Do you want to exit the app",
          "55": "cancel",
          "56": "exit",
          "57": "this email or phone is already registered",
          "58": "verifiycode is not courrct",
          "59": "The email address you entered does not exist",
          "60": "The two passwords must match",
          "61": "Try again later",
          "62": "Something wrong",
          "63": "Find products",
          "64": "A Summer surprise",
          "65": "Cashback 20 %",
          "66": "products for you",
          "67": "over",
          "68": "Find Items",
          "69": "Colors",
          "70": "Go To Cart",
          "71": "success remov items from favorite",
          "72": "success add items to favorite",
          "73": "Disable notifications",
          "74": "Address",
          "75": "About Us",
          "76": "Contact Us",
          "77": "Sign out",
          "78": "Choose your place on the map ",
          "79": "No titles to display, please add a title",
          "80": "The email or password is wrong",
          "81": "Please enter a valid phone number",
          "82": "There are no requests to be displayed in the archive",
          "83": "Deliver",
          "84": "Receive from the store",
          "85": "Cash",
          "86": "Online payment",
          "87": "your order waiting approval",
          "88": "Please add address",
          "": "",
        },
        "ar": {
          "1": "اختر لغتك",
          "2": "ابحث عن العناصر المفضلة لديك",
          "3": "ابحث عن منتجاتك المفضلة التي تحتاج إلى شرائها يوميا",
          "4": "دفع سهل وآمن",
          "5": "ادفع ثمن المنتجات التي تشتريها بأمان وسهولة",
          "6": "تسليم المنتج",
          "7": "يتم تسليم منتجاتك  إلى المنزل بأمن وأمان",
          "8": "التالي",
          "9": "تسجيل الدخول",
          "10": "اهلا بك من جديد",
          "11":
              "يمكنك تسجيل الدخول من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
          "12": " البريد الالكتروني ",
          "13": "ادخل البريد الالكتروني",
          "14": " كلمة المرور",
          "15": "ادخل كلمة المرور",
          "16": "ليس لديك حساب ? ",
          "17": "انشاء حساب",
          "18": "نسيت كلمة المرور",
          "19": "اهلا بك ",
          "20":
              "انشاء حساب من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
          "21": " اسم المستخدم",
          "22": " ادخل اسم المستخدم ",
          "23": " الهاتف ",
          "24": "ادخل رقم الهاتف",
          "25": " لديك حساب ? ",
          "26": " فحص البريد الالكتروني",
          "27": "  ادخل رمز التحقق",
          "28": "تم انشاء الحساب بنجاح",
          "29": "الرجاء ادخال البريد لتلقي رمز التحقق",
          "30": "فحص",
          "31": "الذهاب لتسجيل الدخول",
          "32": "نجاح",
          "33": "حفظ",
          "34": "الرجاء ادخال كلمة المرور الجديدة",
          "35": "الكلمة الجديدة",
          "36": "تم اعادة تعيين كلمة المرور بنجاح",
          "37": "تهانينا",
          "38": "تم التسجيل بنجاح",
          "39": "اٍعادة تعيين كلمة المرور",
          "40": "كلمة المرور الجديدة",
          "41": "ادخل كلمة المرور الجديدة",
          "42": "اٍعادة كلمة المرور",
          "43": " قم باٍعادة كتابة كلمة المرور",
          "44": "اٍعادة تعيين",
          "45": "أدخل البريد الالكتروني من اجل التحقق ",
          "46": "هذه القيمة ليست اسم مستخدم",
          "47": "هذه القيمة ليست  بريد الكتروني",
          "48": "هذه القيمة ليست كلمة مرور",
          "49": "هذه القيمة ليست  رقم هاتف",
          "50": "لا يمكن ادخال قيمة اصغر من",
          "51": "لا يمكنك ادخال قيمة اكبر من",
          "52": "لا يمكنك ادخال قيمة فارغة",
          "53": "تنبيه",
          "54": "هل تريد الخروج من التطبيق",
          "55": "اٍلغاء",
          "56": "خروج",
          "57": "البريد او رقم الهاتف مسجل بالفعل",
          "58": "الرمز الذي ادخلته خاطئ",
          "59": "البريد الالكتروني الذي ادخلته غير موجود",
          "60": "كلمتا المرور غير متطابقتين",
          "61": "اعد المحاولة لاحقا",
          "62": "حدث خطأ",
          "63": "ابحث عن المنتج",
          "64": "عرض الصيف ",
          "65": "خصم %20",
          "66": "منتجات من اجلك",
          "67": "تخفيض",
          "68": "ابحث عن المنتجات",
          "69": "الألوان",
          "70": "اذهب  الى السلة",
          "71": "تم حئف المنتج من المفضلة",
          "72": "تم اضافة المنتج الى المفضلة",
          "73": "تعطيل الاشعارات ",
          "74": "العنوان",
          "75": "معلومات عنا",
          "76": "اتصل بنا",
          "77": "تسجيل الخروج",
          "78": "اختر مكانك على الخريطة ",
          "79": "لا يوجد عناوين لعرضها الرجاء اضافة عنوان",
          "80": "الايميل او كلمة المرور خطا",
          "81": "الرجاء ادخال رقم هاتف صحصح",
          "82": "لا يوجد طلبات لعرضها في الارشيف",
          "83": "توصيل",
          "84": "استلام من المتجر",
          "85": "نقد",
          "86": "دفع الكتروني",
          "87": "طلب بانتظار الموافقة",
          "88": "الرجاء اضافة عنوان",
          "": "",
        },
      };
}
